# shellcheck shell=bash
# shellcheck disable=SC2034
# shellcheck source=/dev/null

CMAKE_RUNTIME_OPTIONS=(
	"-DCMAKE_SYSTEM_NAME=$LLVM_SYSTEM_NAME"
	"-DCMAKE_SYSROOT=${SYSROOT_DIR}"
	"-DCMAKE_C_FLAGS='-resource-dir=$(path_conversion "$RESOURCE_DIR")'"
	"-DCMAKE_CXX_FLAGS='-resource-dir=$(path_conversion "$RESOURCE_DIR")'"
	-DCMAKE_C_COMPILER_WORKS=ON
	-DCMAKE_CXX_COMPILER_WORKS=ON
	"-DCMAKE_C_COMPILER=${CLANG}"
	"-DCMAKE_CXX_COMPILER=${CLANG_PP}"
	"-DCMAKE_AR=${INSTALL_TOOLS_BASE}/llvm_clang/bin/llvm-ar${EXE}"
	"-DCMAKE_RANLIB=${INSTALL_TOOLS_BASE}/llvm_clang/bin/llvm-ranlib${EXE}"
	"-DCMAKE_C_COMPILER_TARGET=${LLVM_TARGET}"
	"-DCMAKE_CXX_COMPILER_TARGET=${LLVM_TARGET}"
);
LLVM_BASE_OPTIONS=(
	-DLLVM_BUILD_LLVM_DYLIB=OFF
    -DLLVM_LINK_LLVM_DYLIB=OFF
    -DLLVM_ENABLE_BINDINGS=OFF
    "-DLLVM_TARGETS_TO_BUILD=$ARCHITECTURES"
	"-DLLVM_DEFAULT_TARGET_TRIPLE=$LLVM_TARGET"
);
CLANG_BASE_OPTIONS=(
	-DCLANG_VENDOR="llvm_moduly ($LLVM_MODULY_VERSION)"
	-DCLANG_DEFAULT_RTLIB=compiler-rt
	-DCLANG_DEFAULT_UNWINDLIB=libunwind
	-DCLANG_DEFAULT_CXX_STDLIB=libc++
	-DCLANG_DEFAULT_LINKER=lld
	-DCLANG_RESOURCE_DIR=../resource
	-DDEFAULT_SYSROOT=../sysroot
);