# shellcheck shell=bash
# shellcheck disable=SC2034
# shellcheck source=/dev/null

CMAKE_OPTIONS=(
	"-DCMAKE_SYSTEM_NAME=$LLVM_SYSTEM_NAME"
	"-DCMAKE_SYSROOT=${SYSROOT_DIR}"
	"-DCMAKE_INSTALL_PREFIX=${RESOURCE_DIR}"
	"-DCMAKE_C_FLAGS='-resource-dir=$(path_conversion "$RESOURCE_DIR")'"
	"-DCMAKE_CXX_FLAGS='-resource-dir=$(path_conversion "$RESOURCE_DIR")'"
	-DCMAKE_C_COMPILER_WORKS=ON
	-DCMAKE_CXX_COMPILER_WORKS=ON
	"-DCMAKE_C_COMPILER=${CLANG}"
	"-DCMAKE_CXX_COMPILER=${CLANG_PP}"
	"-DCMAKE_AR=${INSTALL_TOOLS_BASE}/llvm_clang/bin/llvm-ar${EXE}"
	"-DCMAKE_RANLIB=${INSTALL_TOOLS_BASE}/llvm_clang/bin/llvm-ranlib${EXE}"
	"-DCMAKE_C_COMPILER_TARGET=${LLVM_TARGET}"
);
COMPILER_RT_OPTIONS=(
	-DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON
	-DCOMPILER_RT_BUILD_BUILTINS=ON
	-DCOMPILER_RT_EXCLUDE_ATOMIC_BUILTIN=OFF
	-DCOMPILER_RT_USE_ATOMIC_LIBRARY=ON
	-DCOMPILER_RT_USE_BUILTINS_LIBRARY=OFF
	-DCOMPILER_RT_USE_LIBCXX=ON
	-DCOMPILER_RT_USE_LLVM_UNWINDER=ON
	-DSANITIZER_CXX_ABI=libc++
);
LIBCXX_OPTIONS=(
	-DLIBCXX_USE_COMPILER_RT=ON
	-DLIBCXX_ENABLE_SHARED=OFF
	-DLIBCXX_ENABLE_STATIC=ON
	-DLIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON
	-DLIBCXX_CXX_ABI=libcxxabi
	-DLIBCXX_INSTALL_MODULES=ON
	-DLIBCXX_ENABLE_ABI_LINKER_SCRIPT=OFF
);
LIBCXX_ABI_OPTIONS=(
	-DLIBCXXABI_USE_COMPILER_RT=ON
	-DLIBCXXABI_USE_LLVM_UNWINDER=ON
	-DLIBCXXABI_ENABLE_SHARED=OFF
);
LIBUNWIND_OPTIONS=(
	-DLIBUNWIND_USE_COMPILER_RT=ON
	-DLIBUNWIND_ENABLE_SHARED=OFF
	-DLIBUNWIND_ENABLE_STATIC=ON
);

if [ "$BUILD_TYPE" = "release" ] || [ "$BUILD_TYPE" = "runtime_build" ]
then
	CMAKE_OPTIONS+=(-DCMAKE_BUILD_TYPE=Release);

	LIBUNWIND_OPTIONS+=(
		-DLIBUNWIND_ENABLE_ASSERTIONS=OFF
		-DLIBUNWIND_INCLUDE_TESTS=OFF
	);
	LIBCXX_ABI_OPTIONS+=(
		-DLIBCXXABI_INCLUDE_TESTS=OFF
		-DLIBCXXABI_ENABLE_ASSERTIONS=OFF
	);
	LIBCXX_OPTIONS+=(-DLIBCXX_INCLUDE_TESTS=OFF);

	LLVM_RESOURCE_HEADERS_DIR="${BUILD_BASE}/llvm_resource_headers_${LLVM_TAG}";
	LLVM_RUNTIME_DIR="${BUILD_BASE}/llvm_runtime_${LLVM_TAG}";
elif [ "$BUILD_TYPE" = "runtime_test" ]
then
	CMAKE_OPTIONS+=(-DCMAKE_BUILD_TYPE=RelWithDebInfo);
	
	LIBUNWIND_OPTIONS+=(
		-DLIBUNWIND_ENABLE_ASSERTIONS=ON
		-DLIBUNWIND_INCLUDE_TESTS=ON
	);
	LIBCXX_ABI_OPTIONS+=(
		-DLIBCXXABI_INCLUDE_TESTS=ON
		-DLIBCXXABI_ENABLE_ASSERTIONS=ON
	);
	LIBCXX_OPTIONS+=(-DLIBCXX_INCLUDE_TESTS=ON);

	LLVM_RESOURCE_HEADERS_DIR="${BUILD_BASE}_test/llvm_resource_headers_${LLVM_TAG}";
	LLVM_RUNTIME_DIR="${BUILD_BASE}_test/llvm_runtime_${LLVM_TAG}";
else
    echo "Unknown build type.";
    exit 1;
fi