CMAKE_OPTIONS=(
	"-DCMAKE_SYSTEM_NAME=$LLVM_SYSTEM_NAME"
	"-DCMAKE_INSTALL_PREFIX=${INSTALL_BASE}/lib"
);
LLVM_OPTIONS=(
	-DLLVM_BUILD_LLVM_DYLIB=OFF
    -DLLVM_LINK_LLVM_DYLIB=OFF
    -DLLVM_ENABLE_BINDINGS=OFF
    -DLLVM_INSTALL_TOOLCHAIN_ONLY=OFF
    "-DLLVM_TARGETS_TO_BUILD=$ARCHITECTURES"
	"-DLLVM_DEFAULT_TARGET_TRIPLE=$LLVM_TARGET"
);
CLANG_OPTIONS=(
	-DCLANG_VENDOR="llvm_moduly"
	-DCLANG_DEFAULT_RTLIB=compiler-rt
	-DCLANG_DEFAULT_UNWINDLIB=libunwind
	-DCLANG_DEFAULT_CXX_STDLIB=libc++
	-DCLANG_DEFAULT_LINKER=lld
);
LLD_OPTIONS=(
	-DLLD_VENDOR="llvm_moduly"
);
LIBCLANG_OPTIONS=(
	-DLIBCLANG_BUILD_STATIC=ON
);

if [  "$BUILD_TYPE" = "release" ] || [ "$BUILD_TYPE" = "llvm_build" ] \
	|| [ "$BUILD_TYPE" = "runtime_test" ]
then
	CMAKE_OPTIONS+=(-DCMAKE_BUILD_TYPE=Release);
    LLVM_OPTIONS+=(
        -DLLVM_ENABLE_ASSERTIONS=OFF
        -DLLVM_INCLUDE_TESTS=OFF
        -DLLVM_BUILD_TESTS=OFF
		-DCLANG_INCLUDE_TESTS=OFF
	);
elif [ "$BUILD_TYPE" = "llvm_test" ]
then
	CMAKE_OPTIONS+=(-DCMAKE_BUILD_TYPE=RelWithDebInfo);
    LLVM_OPTIONS=(
        -DLLVM_ENABLE_ASSERTIONS=ON
        -DLLVM_INCLUDE_TESTS=ON
        -DLLVM_BUILD_TESTS=ON
		-DCLANG_INCLUDE_TESTS=ON
	);
fi

if [ -v SYSROOT ]
then
    CMAKE_OPTIONS+=(
		-DCMAKE_FIND_ROOT_PATH="${SYSROOT}" \
  		-DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
  		-DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
  		-DCMAKE_FIND_ROOT_PATH_MODE_PACKAGE=ONLY
    );
fi

if [ "$INCLUDE_DOCS" = "ON" ]
then
    LLVM_OPTIONS+=(
		-DLLVM_INSTALL_DOXYGEN_HTML_DIR=share/doc/llvm
        -DLLVM_ENABLE_DOXYGEN=ON
		-DLLVM_INCLUDE_DOCS=ON
		-DCLANG_INCLUDE_DOCS=ON
    );
fi