# shellcheck shell=bash
# shellcheck disable=SC2034
# shellcheck source=/dev/null

CMAKE_OPTIONS=(
	"-DCMAKE_SYSTEM_NAME=$LLVM_SYSTEM_NAME"
	"-DCMAKE_INSTALL_PREFIX=${INSTALL_BASE}/tmp"
	-DCMAKE_C_COMPILER_WORKS=ON
	-DCMAKE_CXX_COMPILER_WORKS=ON
	"-DCMAKE_C_COMPILER=${INSTALL_BASE}/llvm_clang/bin/clang.exe"
	"-DCMAKE_CXX_COMPILER=${INSTALL_BASE}/llvm_clang/bin/clang++.exe"
	"-DCMAKE_AR=${INSTALL_BASE}/llvm_clang/bin/llvm-ar.exe"
	"-DCMAKE_RANLIB=${INSTALL_BASE}/llvm_clang/bin/llvm-ranlib.exe"
	"-DCMAKE_C_COMPILER_TARGET=${LLVM_TARGET}"
);
BUILTINS_OPTIONS=(
	-DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON
    -DCOMPILER_RT_EXCLUDE_ATOMIC_BUILTIN=OFF
);
LIBCXX_OPTIONS=(
	-DLIBCXX_USE_COMPILER_RT=ON
	-DLIBCXX_ENABLE_SHARED=OFF
	-DLIBCXX_ENABLE_STATIC=ON
	-DLIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON
	-DLIBCXX_CXX_ABI=libcxxabi
	-DLIBCXX_INSTALL_MODULES=ON
	-DLIBCXX_ENABLE_ABI_LINKER_SCRIPT=OFF
);
LIBCXX_ABI_OPTIONS=(
	-DLIBCXXABI_USE_COMPILER_RT=ON
	-DLIBCXXABI_USE_LLVM_UNWINDER=ON
	-DLIBCXXABI_ENABLE_SHARED=OFF
);
LIBUNWIND_OPTIONS=(
	-DLIBUNWIND_USE_COMPILER_RT=ON
	-DLIBUNWIND_ENABLE_SHARED=OFF
	-DLIBUNWIND_ENABLE_STATIC=ON
);

if [ "$BUILD_TYPE" = "release" ] || [ "$BUILD_TYPE" = "runtime_build" ]
then
	CMAKE_OPTIONS+=(-DCMAKE_BUILD_TYPE=Release);

	LIBUNWIND_OPTIONS+=(
		-DLIBUNWIND_ENABLE_ASSERTIONS=OFF
		-DLIBUNWIND_INCLUDE_TESTS=OFF
	);
	LIBCXX_ABI_OPTIONS+=(
		-DLIBCXXABI_INCLUDE_TESTS=OFF
		-DLIBCXXABI_ENABLE_ASSERTIONS=OFF
	);
	LIBCXX_OPTIONS+=(-DLIBCXX_INCLUDE_TESTS=OFF);

	LLVM_BUILTINS_DIR="${BUILD_BASE}/llvm_builtins_${LLVM_TAG}";
	LLVM_RUNTIME_DIR="${BUILD_BASE}/llvm_runtime_${LLVM_TAG}";
elif [ "$BUILD_TYPE" = "runtime_test" ]
then
	CMAKE_OPTIONS+=(-DCMAKE_BUILD_TYPE=RelWithDebInfo);
	
	LIBUNWIND_OPTIONS+=(
		-DLIBUNWIND_ENABLE_ASSERTIONS=ON
		-DLIBUNWIND_INCLUDE_TESTS=ON
	);
	LIBCXX_ABI_OPTIONS+=(
		-DLIBCXXABI_INCLUDE_TESTS=ON
		-DLIBCXXABI_ENABLE_ASSERTIONS=ON
	);
	LIBCXX_OPTIONS+=(-DLIBCXX_INCLUDE_TESTS=ON);

	LLVM_BUILTINS_DIR="${BUILD_BASE}_test/llvm_builtins_${LLVM_TAG}";
	LLVM_RUNTIME_DIR="${BUILD_BASE}_test/llvm_runtime_${LLVM_TAG}";
else
    echo "Unknown build type.";
    exit 1;
fi

if [ -v SYSROOT ]
then
    CMAKE_OPTIONS+=(
		-DCMAKE_SYSROOT="${SYSROOT}"
    );
fi